let COUNTER: number = 0;

export const MAX_UINT8_VALUE = 0xFF;
export const MAX_UINT16_VALUE = 0xFFFF;
export const MAX_UINT32_VALUE = 0xFFFFFFFF;

export const OperationCodes = {
  STACK_PUSH_UINT8: COUNTER++,
  STACK_PUSH_UINT16: COUNTER++,
  STACK_PUSH_UINT32: COUNTER++,
  STACK_PUSH_UNDEFINED: COUNTER++,
  STACK_PUSH_STRING: COUNTER++,
  STACK_PUSH_THIS: COUNTER++,

  BINARY_SUM: COUNTER++,
  BINARY_SUB: COUNTER++,
  BINARY_MUL: COUNTER++,
  BINARY_DIV: COUNTER++,
  BINARY_MOD: COUNTER++,
  
  BINARY_LESS: COUNTER++,
  BINARY_LESS_OR_EQUAL: COUNTER++,
  BINARY_GREATER: COUNTER++,
  BINARY_GREATER_OR_EQUAL: COUNTER++,
  BINARY_EQUAL: COUNTER++,
  BINARY_STRICT_EQUAL: COUNTER++,
  BINARY_NOT_EQUAL: COUNTER++,
  BINARY_STRICT_NOT_EQUAL: COUNTER++,
  
  BINARY_BIT_SHIFT_LEFT: COUNTER++,
  BINARY_BIT_SHIFT_RIGHT: COUNTER++,
  BINARY_UNSIGNED_BIT_SHIFT_RIGHT: COUNTER++,
  BINARY_BIT_XOR: COUNTER++,
  BINARY_BIT_AND: COUNTER++,
  BINARY_BIT_OR: COUNTER++,

  BINARY_IN: COUNTER++,
  BINARY_INSTANCEOF: COUNTER++,

  LOGICAL_AND: COUNTER++,
  LOGICAL_OR: COUNTER++,

  UNARY_PLUS: COUNTER++,
  UNARY_MINUS: COUNTER++,
  UNARY_NOT: COUNTER++,
  UNARY_BIT_NOT: COUNTER++,

  LOAD: COUNTER++,
  STORE: COUNTER++,

  BUILD_ARRAY: COUNTER++,
  BUILD_OBJECT: COUNTER++,

  GET_PROPERTY: COUNTER++,
  SET_PROPERTY: COUNTER++,

  CALL_FUNCTION: COUNTER++,

  REGISTER_STRING: COUNTER++,
} as const;

export const WindowProperties: Set<string> = new Set([
  "alert",
  "prompt",
  "confirm",
  "console",
  "Math",
  "document",
  "String",
  "Number",
  "Boolean",
  "Object",
  "Array",
  "Function",
  "window",
]);